### ISSUE TITLE
Infinite Recursive Depth When Trying to Import winreg And fcntl

### ISSUE THREAD

**Issue by wagrenier** [d0c-s4vage/pipless#15]
On python 2.7 (tested on win10), when the program tries to import module winreg or fcntl it goes into an infinite recursive loop and hangs the program. I can make a pull request to fix this issue.

**Comment by d0c-s4vage** [comment]
Thanks for reporting this! Reopening to investigate

**Comment by wagrenier** [comment]
Also the importer goes too deep and ends up importing dependencies of dependencies of... I fixed it by checking that from where I was importing is inside my project
